name: Build Next.js with Bun

on:
  push:
    branches:
      - main
      - staging
  pull_request:

jobs:

  deploy-docker-app:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Checkout repository
        uses: actions/checkout@v3

       
      - name: Build and Push App
        run: |
          docker buildx build --platform linux/amd64 -t mikelmiras/kmm:latest ./web --push